apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: node-k4
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          ports:
            - containerPort: 389
              name: ldap
            - containerPort: 636
              name: ldaps
          env:
          - name: LDAP_ORGANISATION
            valueFrom:
              configMapKeyRef:
                name: openldap-config
                key: LDAP_ORGANISATION
          - name: LDAP_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: openldap-config
                key: LDAP_DOMAIN
          - name: LDAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: openldap-secrets
                key: LDAP_ADMIN_PASSWORD
          - name: LDAP_CONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: openldap-secrets
                key: LDAP_CONFIG_PASSWORD
          volumeMounts:
            - name: openldap-data
              mountPath: /var/lib/ldap
            - name: openldap-config
              mountPath: /etc/ldap/slapd.d
      volumes:
        - name: openldap-data
          persistentVolumeClaim:
            claimName: openldap-pvc
        - name: openldap-config
          emptyDir: {}
