apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-customconfig
  namespace: nextcloud
data:
  custom.config.php: |-
    <?php
    $CONFIG = array (
        'datadirectory' => '/var/www/html/data',
        // 'config_is_read_only' => true,
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://nextcloud.euchange.eu',
        'filelocking.enabled' => 'true',
        'loglevel' => '2',
        'enable_previews' => true,
        'trusted_domains' =>
             [
                'nextcloud.euchange.eu'
             ]
    );

