apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpldapadmin-ingress
  namespace: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod 
    nginx.ingress.kubernetes.io/enable-access-log: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - phpldapadmin.euchange.eu 
      secretName: phpldapadmin-tls
  rules:
    - host: phpldapadmin.euchange.eu 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpldapadmin
                port:
                  number: 80

