apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phpldapadmin-cert
  namespace: nextcloud
spec:
  secretName: phpldapadmin-tls
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer
  commonName: phpldapadmin.euchange.eu
  dnsNames:
    - phpldapadmin.euchange.eu 

