apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: node-p4
      containers:
        - name: phpldapadmin
          image: osixia/phpldapadmin:0.9.0
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "openldap"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
