apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-config
  namespace: nextcloud
data:
  dovecot.conf: |
    protocols = imap pop3
    listen = *
    mail_location = maildir:/var/mail/%d/%n
    ssl = yes
    ssl_cert = </etc/ssl/certs/dovecot.pem
    ssl_key = </etc/ssl/private/dovecot.key
